services:
  static:
    image: nginx:1.25.3-alpine3.18
    ports:
      - 9000:9000
      - 9001:9001
      - 9002:9002
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
      - ./public:/public

  shell:
    build:
      dockerfile: ../Dockerfile
      context: ./shell
    volumes:
      - ./shell:/app
      - static:/static

  blog:
    image: node:20.9.0-alpine3.18
    volumes:
      - ./blog:/app
      - static:/static

  shop:
    image: node:20.9.0-alpine3.18
    volumes:
      - ./shop:/app
      - static:/static

volumes:
  static:
