services:
  static:
    image: nginx:1.25.3-alpine3.18
    ports:
      - 9000:9000
      - 9001:9001
      - 9002:9002
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/static
      - apps:/apps
      - ./public:/public

  shell:
    environment:
      NODE_ENV: 'development'
    command: yarn start
    build:
      dockerfile: ../Dockerfile
      context: ./shell
    volumes:
      - ./shell:/app
      - static:/static

  blog:
    environment:
      NODE_ENV: 'development'
      APP_NAME: 'blog'
    command: yarn start
    build:
      dockerfile: ../Dockerfile
      context: ./blog
    volumes:
      - ./blog:/app
      - static:/static
      - apps:/apps

  shop:
    environment:
      NODE_ENV: 'development'
      APP_NAME: 'shop'
    command: yarn start
    build:
      dockerfile: ../Dockerfile
      context: ./shop
    volumes:
      - ./shop:/app
      - static:/static
      - apps:/apps

volumes:
  static:
  apps:
